package net.buckleystudios.equigen.entity.custom.genetics.util;

public enum GeneticCategories {
    CONFORMATION_GENETICS,
    COAT_GENETICS,
    COAT_VARIATION_GENETICS,
    PATTERN_GENETICS,
    PATTERN_VARIATION_GENETICS,
    MARKING_GENETICS,
    PERSONALITY_GENETICS,
    PERCENTAGE_GENETICS,
    TRAIT_GENETICS,
    TRAIT_VARIATION_GENETICS,
    LOVE_AND_HATE_GENETICS,
    SKILL_GENETICS,
    ABILITY_GENETICS,
    RANDOM_GENETICS,
    NONE
}
